ARG NODE_VERSION
ARG NODE_VARIANTE
FROM node:${NODE_VERSION}-${NODE_VARIANTE}
LABEL maintainer="tzalejo@gmail.com"
LABEL version="2.0"
WORKDIR /app
EXPOSE ${NPM_PORT_CONTAINER}
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
