networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_VOLUMEN_PATH}:/var/www/html
    depends_on:
      - php
      - pgsql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - APP_PHP_VERSION
        - APP_PHP_VARIANTE
    container_name: php
    volumes:
      - ${APP_VOLUMEN_PATH}:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
      args:
        - COMPOSER_VERSION=${COMPOSER_VERSION}
    container_name: composer
    volumes:
      - ${APP_VOLUMEN_PATH}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel

  vite:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - NPM_NODE_VERSION
        - NPM_NODE_VARIANTE
    container_name: vite
    ports:
      - "${NPM_PORT}:${NPM_PORT_CONTAINER}"
    volumes:
      - ${NPM_VOLUMEN_PATH}:/app
    user: "1000:1000"
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - APP_PHP_VERSION
        - APP_PHP_VARIANTE
    container_name: artisan
    volumes:
      - ${APP_VOLUMEN_PATH}:/var/www/html
    depends_on:
      - pgsql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel

  cron:
    build:
      context: .
      dockerfile: cron.dockerfile
      args:
        - APP_PHP_VERSION
        - APP_PHP_VARIANTE
    container_name: cron
    volumes:
      - ${APP_VOLUMEN_PATH}:/var/www/html
    depends_on:
      - pgsql
    networks:
      - laravel

  supervisor-worker:
    build:
      context: .
      dockerfile: worker.dockerfile
      args:
        - APP_PHP_VERSION
        - APP_PHP_VARIANTE
    container_name: supervisor-worker
    restart: unless-stopped
    depends_on:
      - pgsql
    entrypoint: ["/usr/local/bin/docker-entrypoint-fix-storage-perms.sh"]
    command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
    volumes:
      - ${APP_VOLUMEN_PATH}:/var/www/html:delegated
      - ./php-worker/supervisord.d:/etc/supervisord.d
    networks:
      - laravel

  pgsql:
    image: postgres:${POSTGRES_VERSION}
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUMEN_PATH}:/var/lib/postgresql/data
    networks:
      - laravel
