ARG NPM_NODE_VERSION=22
ARG NPM_NODE_VARIANTE=alpine
FROM node:${NPM_NODE_VERSION}-${NPM_NODE_VARIANTE}
LABEL maintainer="tzalejo@gmail.com"
LABEL version="2.0"
WORKDIR /app
EXPOSE ${NPM_PORT_CONTAINER}
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
